from app.exceptions.base import SyncmasterException


class UsernameAlreadyExists(SyncmasterException):
    pass
